
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAREND = 30;
  public static final int RESTO = 45;
  public static final int DIVIDE = 26;
  public static final int COLCHEE = 50;
  public static final int IGUALI = 34;
  public static final int FUNCTION = 10;
  public static final int COLCHED = 51;
  public static final int EXPO = 44;
  public static final int REPEAT = 17;
  public static final int INT = 48;
  public static final int MENORI = 37;
  public static final int MAIORI = 38;
  public static final int FOR = 9;
  public static final int PONTO = 39;
  public static final int NOT = 15;
  public static final int AND = 2;
  public static final int PONTOS = 40;
  public static final int ELSEIF = 6;
  public static final int IGUAL = 33;
  public static final int CHAVEE = 31;
  public static final int VIRG = 28;
  public static final int NIL = 14;
  public static final int CHAVED = 32;
  public static final int IN = 12;
  public static final int OR = 16;
  public static final int MAIS = 24;
  public static final int UNTIL = 21;
  public static final int IF = 11;
  public static final int PVIRG = 27;
  public static final int TILI = 41;
  public static final int DPONTOS = 42;
  public static final int EOF = 0;
  public static final int TPONTOS = 43;
  public static final int RETURN = 18;
  public static final int MAIOR = 36;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int MENOS = 25;
  public static final int MENOR = 35;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int TRALHA = 46;
  public static final int REAL = 49;
  public static final int ELSE = 5;
  public static final int WHILE = 22;
  public static final int THEN = 19;
  public static final int END = 7;
  public static final int STRING = 52;
  public static final int LOCAL = 13;
  public static final int FALSE = 8;
  public static final int VEZES = 23;
  public static final int DO = 4;
  public static final int PARENE = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "BREAK",
  "DO",
  "ELSE",
  "ELSEIF",
  "END",
  "FALSE",
  "FOR",
  "FUNCTION",
  "IF",
  "IN",
  "LOCAL",
  "NIL",
  "NOT",
  "OR",
  "REPEAT",
  "RETURN",
  "THEN",
  "TRUE",
  "UNTIL",
  "WHILE",
  "VEZES",
  "MAIS",
  "MENOS",
  "DIVIDE",
  "PVIRG",
  "VIRG",
  "PARENE",
  "PAREND",
  "CHAVEE",
  "CHAVED",
  "IGUAL",
  "IGUALI",
  "MENOR",
  "MAIOR",
  "MENORI",
  "MAIORI",
  "PONTO",
  "PONTOS",
  "TILI",
  "DPONTOS",
  "TPONTOS",
  "EXPO",
  "RESTO",
  "TRALHA",
  "IDENT",
  "INT",
  "REAL",
  "COLCHEE",
  "COLCHED",
  "STRING"
  };
}

